version: "2"
services:
  node:
    image: node
    volumes:
      - ./node:/app
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="/app/gcp_credentials.json"
    command: npm start
  nginx:
    image: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./static:/var/www/html
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./certbot/conf/:/etc/nginx/ssl/
    network_mode: "service:node"
    depends_on:
      - node
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email omar.nassif98@gmail.com --agree-tos --no-eff-email -d recall.omarnassif.me